// <auto-generated />
namespace ProjectFood.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Ingredient_Recipe_Many_Relate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ingredient_Recipe_Many_Relate));
        
        string IMigrationMetadata.Id
        {
            get { return "201511150300491_Ingredient_Recipe_Many_Relate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
