// <auto-generated />
namespace ProjectFood.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class ASPNET_Identity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ASPNET_Identity));
        
        string IMigrationMetadata.Id
        {
            get { return "201510270310495_ASPNET_Identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
