// <auto-generated />
namespace ProjectFood.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class CommentsAddition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CommentsAddition));
        
        string IMigrationMetadata.Id
        {
            get { return "201512082018403_CommentsAddition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
